function paths = work01_paths()
%WORK01_PATHS Resolve Work 01 locations without relying on the current folder.

matlabRoot = fileparts(mfilename('fullpath'));
codeRoot = fileparts(matlabRoot);
workRoot = fileparts(codeRoot);
assetsRoot = fullfile(workRoot, 'assets');
paths = struct( ...
    'matlab_root', matlabRoot, ...
    'code_root', codeRoot, ...
    'work_root', workRoot, ...
    'assets_root', assetsRoot, ...
    'data_dir', fullfile(assetsRoot, 'data'), ...
    'figures_dir', fullfile(assetsRoot, 'figures'), ...
    'tables_dir', fullfile(assetsRoot, 'tables'), ...
    'docs_dir', fullfile(workRoot, 'docs'));
end
